
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIHOST: AgBVVaaLgz6A/nO7y3FilULLLnB6t3dHzAKEKrnFRD+GRuwun28Slk42TIG7Wt+TTClfOjKJOpqmXF+FBNLLHJQsbRgYsd28aVzX9iHlmEWYBYkbRCaUeeZY/KhrcrapWKbjubD0tPmdhA0Z9D75dUoI63wLohrem7YWX2TpmlIDJilTGrxTkLWWNn/YozgoYHrMOeaTS30t4dHXrNNjrKQAtCydBkMaCy9GnTbjas5eisyxq0/we5J763yZu3FldTJZ7idPyfT+r1aBY/guQOspxuXYlIrRCmpHPURsuVkjb4wjUHyU06lfZlUS5HZ/rnNzPXfaFQED1yBr++kdxuITWX+kCoHTv5BDYW5whzXU74ONKvc6g1KiLYzhH7nNOASH85O2tXvCeIgI0obuscS5qyh9GTD701dLp9J5At/UilXai5BEDXg793nudgrxfTpOMY/2UG0GxI22vIAIVKCZ9Js/WDo3Y6ReT8cKlREBBKQloaR/p5RM2kaF9foIijCV8qK+a3LUo359jdGrd+a20VqSL0D5Urx0GJ64H7yX1Kf5hyqJs2fn27mSC7DrSp2OV3VYhv4/1BfuQczN0t8ex9x07mh64mCIyiqVvvVLzo5EaMbeFa16ejTdHfyZo1W+wyBJmXe8y6NGKZISzNRVPMt8TrbPsyh9uoONHBNdR+99qQd+k1bd2Yh/fo2+1zFog0x5pH/uJS8DfYLQT4wMl1w4qhc/2UQ9d5wF4F9NYQ==
    APIKEY: AgDQgXQKazZtNhbOUm6Hlu8kGbaJwySuyecuPYy1y1VnU60aXLApz53xEViVIWftG6O7NDkNmHRK/yWPT5Rs2H/+UkeTYLL5uPNtfJcAcFw1UClpVzL9UY8UsiUyy9ltiAqUQG1ewuG6Vd0zNfy1i/x4nSVL4ZB6tLoafX6fSpF5f1Kl69lUKe9phSZuEJf55Ab4WEEhKMJAmzmoP9uQax463PBYekm3IPRjLaBIeM1x5pxGlhzo+UfsBOPyeF9BYEQnnJ6j6qbs4ZaTRoCAqqgbQx86La5QLwV6fdr7WAQJdm77xdQIdL68xs2vsjf/dOMbOBuf6QI90rWtRUTWXKSoHrQDquDqjV1s2xRT3L7XHAndIHE7jAlQlpz8zXe3fU7RRl3JJswmL5aAnZ0zKC8hCbyVroCXkEYPuMwKHr+MyDlLFmEjHm7ZNfgCmfmbYJH8XhCJ/wlwgKAcYTBbVcx5IWW2vFtnXFL88m6eowWxjrSBwZ9kPRIFdzpYzJVFS2tpqcimIoAK/FIGwdCFOrohNxExYGnoASG5TLD2XcHb0iDbGuuDucrVD5/nokpc2zF/pSfXec/6rM9Am9A98Y6lwDGiAALO4l67VtMaa4q4cbay29nxK9dyMthoRpe9C6ug56NawlisMHu0ZcpiMtbX6xhAGiaw2drciH09Ai54kzJPytIwWBTEePzFaT0axPF3XjUTC6xZjzPgIlmR27YfUyQx5L2swddPx3EBz8UfSyVH1m+2wKhE4oE+s3kRec2Sjw==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
