apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgA3NAeBqnME2ZEofeTbXPqF2jxCUsH5Y8tuQaIndPjzWIan0jEr0hpyualz94hOOYx9QSR+/aWBJIGebqNkYwvJUSLoQf4m895nn3QFPKNNQiYnAM9rLAG3rnR05qdB0Seq9yjqbp+ezh95Di7itmCzn5X0ajaBbzk+2c0HeN/HrpLrtIuuUbJnt60qh0GFwjyqTm9PPYhdEygvo85RCpitNtNAuJu4LIuCK3SU19gxLHa7Cttg47Z3g0mrlgBIilcO4ofPf3/MOI7J7eEOODlALSVOGjoGeWyzVgSoRtj7AS2GGLDlZnv2MuGA0DpQk1vixoAgMgCbd5tNfr/P8qtRMqjlMtz+ll8fvHCIfQws9kuhUHCroKLkzHzLM3mK86N4DXuG5+IWK2ovkNlUWUweSohesOJr2dgNlZQRb6FytL7OGV38PfBKEp5KqnnYxfbKec/8RGpYCK94aUc50Fs/4zwSPVOZ6MgH792I7yAoAodEhVQZpKlyjxVdDF9Y1tl80uEAZNmgi9S4f+P2E9kAhPyig2g8w72t0hzeimWbB5oa6A91QESoCrQlCl/NdZl8OK5e2smrndXz8ZQ24mq72e0JdcyJ32uCO7f94GcYyovaIL82DFiyjdzYv3/V3f3hN5o/91G1Gc+xUOqiKIGmSf6wNEu+kTTqZm28xv+dV0YxUDHUKBWpkexSI08HPx5ffIEy9kVfva/g/0RgPh1PkfShBugYo0h8l0aClkvwxM5UMpwUT0R6UunWs2X1vCbugg==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
